name: CI/CD Elixir

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest 
    name: Compile

    env:
      MIX_ENV: test
      ImageOS: ubuntu22
    
    steps:
      - name: Cache deps dir
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: |
            deps
            _build
          key: mix-${{ hashFiles('mix.lock') }}
          restore-keys: |
            mix-

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1.17.3
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Get dependencies
        run: mix deps.get

      - name: Compile
        run: mix compile --warnings-as-errors
